#!/bin/sh

commit_message=$(cat "$1")

regex="^(feat|fix|docs|style|refactor|test|chore|perf|ci|build|revert)\(([A-Z]*[0-9]+-[1-9][0-9]*)\): .{1,50}$"

if ! echo "$commit_message" | grep -Eq "$regex"; then
  echo "ERROR: Commit message does not follow Conventional Commits guidelines."
  echo ""
  echo "Commit message format:"
  echo "  <type>(TEAM-<jira-ticket-number>): <description>"
  echo ""
  echo "Example:"
  echo "  feat(G10-215): add login functionality"
  echo ""
  echo "Allowed types: feat, fix, docs, style, refactor, test, chore, perf, ci, build, revert"
  echo "Note: The Jira ticket must be valid"
  exit 1
fi
